spring.application.name=LDAPAuthentication
spring.datasource.url=jdbc:oracle:thin:@192.168.192.51:1521/aithpdb
spring.datasource.username=ESEC_NEW_MIG
spring.datasource.password=esec_new_mig
spring.datasource.driver.class=oracle.jdbc.driver.OracleDriver
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.Oracle10gDialect
#
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=20000 
spring.datasource.hikari.idle-timeout=300000 
spring.datasource.hikari.max-lifetime=1200000

#ldap.url=ldap://localhost:10389/
#ldap.bases=ou=people,dc=example,dc=com;ou=people,ou=system;ou=user,o=demoserver	
#ldap.bases=ou=people,dc=example,dc=com;ou=aithent,ou=system
#ldap.bases=ou=people,ou=system;ou=user,o=demoserver;ou=people,dc=example,dc=com

#ldap.user=uid=admin,ou=system
#ldap.password=secret

# Security protocol
ldap.security.protocol=ssl

# SSL configuration
#ldap.ssl.key-store=classpath:keystore.jks
#ldap.ssl.key-store-password=changeit
#ldap.ssl.key-store-type=JKS
#ldap.ssl.trust-store=classpath:truststore.jks
#ldap.ssl.trust-store-password=changeit
#ldap.ssl.trust-store-type=JKSapacheds


# Search configuration
ldap.search.subfolders=true
ldap.dn.count=2
ldap.search.filter=(&(objectClass=person)(cn=<loginname>))


app.jwtExpirationInMs = 604800000
#spring.ldap.embedded.ldif=classpath:farixs.ldif
#spring.ldap.embedded.base-dn=dc=example,dc=com
#spring.ldap.embedded.port=10389
#spring.ldap.embedded.url=ldap://localhost:10389/
spring.ldap.userid=uid
ldap.user.commanName=cn
ldap.user.password=userPassword
authserver.jwtSecret= 357638792F423F4428472B4B6250655368566D597133743677397A2443264629

authserver.jwtExpirationMs= 36000000
authserver.jwtRefreshExpirationMs= 86400000

aithentkey=aithentrandomkey
secretkey=eSecurity aithent

server.port = 8889
a2oruServiceURL=http://localhost:8989
a2oruAuthenticationServiceURL =http://localhost:9999
saveUsers=/api/v5/organizations/saveIndividualOrOrganizationUser
authUser = /api/v5/auth/byloginName
client.secret=g6r/f9cj/e2Du6KMXXYNzCsb9TvIwNulYi3PfsC9pQsg6ZVkovujvCcNWQMTinBCWLPw/3Gc8fTKAalyG0Yxh8FxlZmuUqZghhNb/ZPQTanC42EdKcfb+s0OI8n+J0cMUf+BmPNOIJayg9Onm5WhWfUFzuGL2wWbjZIA9emjqXk=
exception.print.stackTraceValue=true
eureka.client.enabled=false
groupDN =ou=groups,ou=system;




